### ISSUE TITLE
Band pass frequency range - what is it for?

### ISSUE THREAD

**Issue by tdent** [jkanner/pe-viewer#36]
I looked at the page and the thing that stood out as not what I expected for a PE plotting webpage was the 'Band pass frequency range' slider.  I can't work out what this controls and what someone might use it for.  For example it might have some effect on the 'waveform' display, but having tried that it doesn't seem to do so. 

So I am a bit stumped by this.

**Comment by tdent** [comment]
Oh, there is more content under the audio file under 'Waveform' .. I guess that ('Project waveform onto each detector') is what is being controlled here? 
In any case, the fact that the bandpass slider has zero effect on almost all the displayed plots is likely to be confusing.

**Comment by jkanner** [comment]
Thanks, @tdent !  I appreciate the feedback.

Yes - you've correctly figured out that the band-pass filter only applies to the waveform and data projected onto each IFO.  

I agree with you this is confusing in the app, and I should try to find a way to make it more clear.

I could put the slider right above the impacted waveform, but I worry having the controls "in-line" might make them difficult to use while the app is reloading.  I could certainly add a note to say what this control does.  In any case, I agree that this is confusing in the current state.  Thank you for flagging it.

**Comment by jkanner** [comment]
done in branch
