### ISSUE TITLE
Typo in waveform section

### ISSUE THREAD

**Issue by tdent** [jkanner/pe-viewer#37]
"Finding maxium likelihood sample ..."

**Comment by jkanner** [comment]
@tdent 
I think this comment is noting the typo in the word "maxium" ... right?

Good catch.  Thanks.

**Comment by jkanner** [comment]
Though - if you want my opinion, `Maxium` is a pretty cool word.  Sort of a mash-up of "maximum" and "axiom".  

Could be used to mean "The best possible assumption for a given problem."  

For example, "In considering climate change, we accept the `maxium` that the extinction of all life on earth is an undesirable outcome."

Anyway, I'll fix the typo.

**Comment by jkanner** [comment]
done in branch
