### ISSUE TITLE
How persistent is the cache?

### ISSUE THREAD

**Issue by jkanner** [jkanner/pe-viewer#45]
@philippeg-ligo  

I've added a new feature to the peviewer app that allows a user to build up the entire cache.  This takes a couple hours, and fills 18 GB of storage with all the data needed by the app.

My question is: in the current deployment, how persistent is the storage?  My thought was that it would last until I pushed a new deployment of the app, but I noticed today it seemed to clear out, and I didn't know why.  Is that expected?  For example, does kubernetes routinely wipe the storage of the app?

**Comment by philippeg-ligo** [comment]
per se Kubernetes does not "wipe the storage". However I have not yet converged in persistent storage. So the response to the question is : 

the cache persists for the lifetime of the container. 

in a kubernetes containers get destroyed and restarted under many circumstances, deployment of a new version is but one of the possible events.

**Comment by jkanner** [comment]
Thank you, @philippeg-ligo !  That makes sense.
